FROM node:9.5 as builder

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

COPY static/ /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

ADD ./static/package.json /usr/src/app/package.json
RUN npm install
RUN npm install -g react-scripts@1.1.1

CMD ["npm", "start"]