FROM node:9.5 as builder

RUN mkdir /usr/src/app
WORKDIR /usr/src/app

COPY static/ /usr/src/app

ENV PATH /usr/src/app/node_modules/.bin:$PATH

ADD ./static/package.json /usr/src/app/package.json
RUN npm install
RUN npm install -g react-scripts@1.1.1
RUN npm run build

FROM nginx:1.13.3-alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=builder /usr/src/app/build /usr/share/nginx/html
COPY config/nginx.conf /etc/nginx/conf.default

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]